---
- hosts: Flocked-LB


  vars:
        app_name: Flocked-LB
        app_path: /home/ubuntu/{{app_name}}/


  gather_facts: False


  become: yes


  tasks:
        - name: INSTALL PYTHON2
          raw: sudo apt-get -y install python-simplejson


        - name: INSTALL PACKAGES FROM APT
          apt: pkg={{ item }} state=present update_cache=true
          with_items:
                - git
                - nginx
                - upstart


        - name: CLONING REPO
          git: 
                repo: https://github.com/grascj/{{app_name}}.git 
                dest: "{{app_path}}" 
                accept_hostkey: true 
                version: master
                force: yes


        - name: MOVING CONF FILE
          command: mv {{app_path}}ansible/nginx.conf /etc/nginx/nginx.conf


        - name: START NGINX
          command: service nginx restart
          when: started|succeeded


